apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: DCT-Cluster
  region: us-east-1
  version: "1.30"

managedNodeGroups:
  - name: app-nodes
    instanceTypes: ["t3.medium"]
    minSize: 1
    desiredCapacity: 1
    maxSize: 2
    volumeSize: 40
    iam:
      withAddonPolicies:
        ebs: true
        cloudWatch: true
        autoScaler: true

iam:
  withOIDC: true
